define([], function() {
  return {
    "PropertyPaneDescription": "Customize your social feed",
    "WebpartSettings":"Webpart Settings",
    "EnableTwitter":"Enable Twitter",
    "EnableInstagram":"Enable Instagram",
    "EnableFacebook":"Enable Facebook",
    "EnableLinkedIn":"Enable LinkedIn",
    "TwitterGroupSettings": "Twitter Setting",
    "TwitterAccount": "Twitter Account (alias)",
    "ErrorSelectTwitterAccount":"Please edit this Web Part and configure a Twitter account",
    "TwitterLimit": "Feeds limit",
    "TwitterHeader": "Show header",
    "TwitterFooter": "Show footer",
    "TwitterBorders": "Show borders",
    "TwitterScrollbars": "Show scrollbars",
    "InstragramGroupSettings":"Instagram Setting",
    "InstagramUserName":"Instragram User Name",
    "InsagramAccessKey":"Access Key",
    "InstagramFeedLimit":"Limit",
    "InstragramOverlay":"Overlay",
    "FacebookUserName":"Facebook UserName",
    "FaceBookGroupSettings":"Facebook Setting",
    "FacebookHeightFieldLabel":"Page Height",
    "FacebookSmallHeaderFieldLabel":"Small header",
    "FacebookHideCoverFieldLabel":"Hide cover",
    "FacebookShowFacepileFieldLabel":"Show facepile",
    "FacebookBackgroundColorLabel":"Facebook Background Color",
    "InstagramBackgroundColorLabel":"Instagram Background Color",
    "TwitterBackgroundColorLabel":"Twitter Background Color",
    "LinkedInGroupSettings":"LinkedIn Settings",
    "LinkedInBackgroundColorLabel":"LinkedIn Background Color"
  }
});
